---
- hosts: os10-LEAF-1
  connection: network_cli
  gather_facts: false
  collections:
    - dellemc.os10

  vars:
    pings: 2

  tasks: 
    - name: Run connectivity ping tests
      any_errors_fatal: true
      os10_command:
        commands:
          - ping vrf Vrf1 -c{{ pings }} {{ item }} 

        retries: 2
      
        wait_for:
          - result[0] contains "{{ pings }} packets transmitted, {{ pings }} received, 0% packet loss" 

      with_items:
         - 172.16.1.11
         - 172.16.1.12
         - 172.16.2.11
         - 172.16.2.12

      register: ping_log
      
    - name: Print log results of Ping tests
      debug:
        var: ping_log

   
