---
- hosts: os10-LEAF-1
  connection: network_cli
  gather_facts: false
  collections:
    - dellemc.os10

  tasks: 
    - name: Run connectivity ping tests
      os10_command:
        commands:
          - ping vrf Vrf1 -c5 172.16.1.11
          - ping vrf Vrf1 -c5 172.16.1.12
          - ping vrf Vrf1 -c5 172.16.2.11
          - ping vrf Vrf1 -c5 172.16.2.12
          - ping vrf Vrf1 -c5 172.16.1.13
          - ping vrf Vrf1 -c5 1.2.3.4

      register: ping_log
      
    - debug:
        var: ping_log.stdout_lines

